Beltek.HelloMVC/Controllers/OgrenciController.cs
using Beltek.HelloMVC.Models;
using Beltek.HelloMVC.Models.DTO;
using Microsoft.AspNetCore.Mvc;
using System.Collections;

namespace Beltek.HelloMVC.Controllers
{
    public class OgrenciController : Controller
    {//URL Routing
        public ViewResult Index()//Action Metod
        {
            return View();
        }

        public ViewResult OgrenciEkle()
        {
            return View("AddStudent");
        }

        public ViewResult OgrenciDetay(int id)
        {
            Ogrenci ogrenci = null;
            Ogretmen ogretmen = null;

            if (id == 1)
            {
                ogrenci = new Ogrenci(1, "Ali", "Veli");
                //ogretmen = new Ogretmen { Id = 1, Ad = "Osman", Soyad = "Yıldız", Alan = "Matematik" };
            }
            else if (id == 2)
            {
                ogrenci = new Ogrenci(2, "Ahmet", "Mehmet");
                //ogretmen = new Ogretmen { Id = 2, Ad = "Veysel", Soyad = "Yılmaz", Alan = "Türkçe" };
            }

            ViewData["ogr"] = ogrenci;

            ViewBag.student = ogrenci;

            var dto = new OgrenciDTO();
            dto.Teacher = ogretmen;
            dto.Student = ogrenci;

            return View(dto);
        }

        public ViewResult OgrenciListe()
        {
            var ogr = new Ogrenci(1, "Ahmet", "Soyad");
            var ogr1 = new Ogrenci(2, "Ali", "Veli");

            Ogrenci[] ogrenciler = new Ogrenci[2];
            ogrenciler[0] = ogr;
            ogrenciler[1] = ogr1;

            ViewData["students"] = ogrenciler;
            ViewBag.ogrenciler = ogrenciler;

            return View(ogrenciler);
        }

        public ViewResult StudentList()
        {
            var ogr = new Ogrenci(1, "Ahmet", "Soyad");
            var ogr1 = new Ogrenci(2, "Ali", "Veli");

            var lst = new List<Ogrenci> { ogr, ogr1 };
            return View(lst);
        }
    }
}

//Controller'dan View'e Veri Taşıma
//ViewData: Key-Value çiftlerinden oluşan bir koleksiyondur. Keylerin veri tipleri string, value'ların veri tipleri object'dir.
//ViewBag: ViewData ile aynı key-value koleksiyonunu kullanır. Bu nedenle key'ler verilirken dikkat edilmelidir.
//ViewModel: Controller'dan View'e View() metodu aracılığı ile veri taşıma. View() metoduna gönderilen veri, View tarafında @model ifadesi ile karşılandıktan sonra, View içerisinde istenilen yerde @Model ifadesi ile ulaşılarak kullanılabilir. Bu yöntemde taşınan veriler de object tipindedir. 

//DTO: Data Transfer Object: Birden fazla veri tipinde olan değerleri modellemek amacıyla kullanılan classlardır.

Beltek.HelloMVC/Controllers/OgretmenController.cs
using Beltek.HelloMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net;

namespace Beltek.HelloMVC.Controllers
{
    public class OgretmenController : Controller
    {
        public IActionResult Index()
        {
            return RedirectToAction("ListOgretmen");
        }
        public IActionResult AddOgretmen()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddOgretmen(Ogretmen ogrt)
        {
            if (!tckontrol(ogrt.Tckimlik))
            {
                ViewData["Error"] = "TCKimlik 11 haneli olmalıdır ve sadece sayısal değer içermelidir.";
                return View();
            }

            using (var ctx = new OkulDbContext())
            {
                ctx.Ogretmenler.Add(ogrt);
                ctx.SaveChanges();
            }
            return RedirectToAction("ListOgretmen");
        }

        private bool tckontrol(string tckimlik)
        {

            return !string.IsNullOrEmpty(tckimlik) && tckimlik.Length == 11 && tckimlik.All(char.IsDigit);
        }


        public IActionResult ListOgretmen()
        {
            List<Ogretmen> lst;
            using (var ctx = new OkulDbContext())
            {
                lst = ctx.Ogretmenler.ToList();
            }

            return View(lst);
        }
        public IActionResult DeleteOgretmen(string id)
        {
            using (var ctx = new OkulDbContext())
            {
                var ogrtDelet = ctx.Ogretmenler.FirstOrDefault(o => o.Tckimlik == id);

                if (ogrtDelet != null)
                {
                    ctx.Ogretmenler.Remove(ogrtDelet);
                    ctx.SaveChanges();
                    return RedirectToAction("ListOgretmen");
                }

                return NotFound("Silinecek öğretmen bulunamadı");
            }
        }


        public IActionResult UpdateOgretmen(string id)
        {
            Ogretmen ogrt;
            using (var ctx = new OkulDbContext())
            {
                ogrt =ctx.Ogretmenler.FirstOrDefault(o => o.Tckimlik == id);
            }

            if (ogrt == null)
            {
                return NotFound("Öğretmen bulunamadı");
            }

            return View(ogrt);
        }
        [HttpPost]
        public IActionResult UpdateOgretmen(Ogretmen ogrt)
        {
            using (var ctx = new OkulDbContext())
            {
                ctx.Entry(ogrt).State = EntityState.Modified;
                ctx.SaveChanges();
            }
            return RedirectToAction("ListOgretmen");

        }

    }

}

Beltek.HelloMVC/Controllers/StudentController.cs
using Beltek.HelloMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Beltek.HelloMVC.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            return RedirectToAction("ListStudent");
        }

        [HttpGet]
        public IActionResult AddStudent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddStudent(Ogrenci ogr)
        {
            using (var ctx = new OkulDbContext())
            {
                ctx.Ogrenciler.Add(ogr);
                ctx.SaveChanges();
            }
            return RedirectToAction("ListStudent");
        }

        public IActionResult ListStudent()
        {
            List<Ogrenci> lst;
            using (var ctx = new OkulDbContext())
            {
                lst = ctx.Ogrenciler.ToList();
            }

            return View(lst);
        }

        public IActionResult DeleteStudent(int id)
        {
            using (var ctx = new OkulDbContext())
            {
                var ogr = ctx.Ogrenciler.Find(id);
                ctx.Ogrenciler.Remove(ogr);
                ctx.SaveChanges();
            }
            return RedirectToAction("ListStudent");
        }


        public IActionResult UpdateStudent(int id)
        {
            Ogrenci ogr;
            using (var ctx = new OkulDbContext())
            {
                ogr = ctx.Ogrenciler.Find(id);
            }
            return View(ogr);
        }

        [HttpPost]
        public IActionResult UpdateStudent(Ogrenci ogr)
        {
            using (var ctx=new OkulDbContext())
            {
                ctx.Entry(ogr).State = EntityState.Modified;
                ctx.SaveChanges();
            }
            return RedirectToAction("ListStudent");
        }

    }
}

Beltek.HelloMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Beltek.HelloMVC</title>
    <meta name="description" content="@ViewData["Description"]" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Beltek.HelloMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Beltek.HelloMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Ogrenci" asp-action="Index" class="nav-link text-dark">Öğrenci İşlemleri</a>
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Öğrenci Listesi","ListStudent","Student",null,new{@class="nav-link text-dark"})
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Öğretmen Listesi", "ListOgretmen", "Ogretmen", null, new { @class = "nav-link text-dark" })
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Beltek.HelloMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>